version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - XMLA_URL=${XMLA_URL}
      - XMLA_USERNAME=${XMLA_USERNAME}
      - XMLA_PASSWORD=${XMLA_PASSWORD}
      - XMLA_CATALOG=${XMLA_CATALOG}
